name: Deploy Go Application

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker image
              run: docker build -t chicken78182/cvwo-backend ./backend

            - name: Push Docker image
              run: docker push chicken78182/cvwo-backend:latest

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull Docker image
              run: docker pull chicken78182/cvwo-backend:latest

            - name: Delete old container if exists
              run: docker rm -f backend-container || true

            - name: Run Docker container
              run: |
                  docker run -d \
                    -e PORT=${{ secrets.PORT }} \
                    -e ENV=${{ secrets.ENV }} \
                    -e DB_HOST=${{ secrets.DB_HOST }} \
                    -e DB_PORT=${{ secrets.DB_PORT }} \
                    -e DB_USER=${{ secrets.DB_USER }} \
                    -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
                    -e DB_NAME=${{ secrets.DB_NAME }} \
                    -e DB_SSLMODE=${{ secrets.DB_SSLMODE }} \
                    -e DB_CHANNEL_BINDING=${{ secrets.DB_CHANNEL_BINDING }} \
                    -e SECRET=${{ secrets.SECRET }} \
                    -e FRONTEND_URL=${{ secrets.FRONTEND_URL }} \
                    -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
                    -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
                    -e CLOUDFRONT_DISTRIBUTION_ID=${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
                    -p 4040:4040 \
                    --name backend-container \
                    chicken78182/cvwo-backend
