name: Deploy Go Application

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Source
              uses: actions/checkout@v4

            - name: Set up Env variables
              run: |
                  echo "PORT=${{ secrets.PORT }}" >> .env
                  echo "ENV=${{ secrets.ENV }}" >> .env
                  echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
                  echo "DB_USER=${{ secrets.DB_USER }}" >> .env
                  echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
                  echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
                  echo "DB_SSLMODE=${{ secrets.DB_SSLMODE }}" >> .env
                  echo "DB_CHANNEL_BINDING=${{ secrets.DB_CHANNEL_BINDING }}" >> .env
                  echo "SECRET=${{ secrets.SECRET }}" >> .env
                  echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env
                  echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
                  echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
                  echo "CLOUDFRONT_DISTRIBUTION_ID=${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" >> .env

            - name: Login to docker hub
              run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

            - name: Build docker image 
              run: docker build -t chicken78182/cvwo-backend .
            
            - name: Push to docker hub
              run: docker push chicken78182/cvwo-backend:latest
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull docker image
              run: docker pull chicken78182/cvwo-backend:latest
            
            - name: Delete old container
              run: docker rm -f backend-container

            - name: Run docker container 
              run: docker run -d -p 4040:4040 --name backend-container chicken78182/cvwo-backend
            

